---
apiVersion: v1
kind: Namespace
metadata:
  name: animals
  labels:
    client: lion
---
apiVersion: v1
kind: Pod
metadata:
  name: lion-server
  namespace: animals
  labels:
    client: lion
    app: web-server
spec:
  containers:
  - name: lino-app
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lion-server-service
  namespace: animals
  labels:
    client: lion
spec:
  type: ClusterIP
  selector:
    app: web-servers
  ports:
  - port: 80
