---
apiVersion: v1
kind: Namespace
metadata:
  name: applicationservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ado-service-account-applicationservice
  namespace: applicationservice
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ado-admin-ado-service-account-applicationservice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ado-service-account-applicationservice
  namespace: applicationservice
