---
apiVersion: v1
kind: Namespace
metadata:
  name: ui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ado-service-account-ui
  namespace: ui
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ado-admin-ado-service-account-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ado-service-account-ui
  namespace: ui


# kubectl get secret $(kubectl get serviceAccounts ado-service-account-ui -n ui -o=jsonpath={.secrets[*].name}) -n ui -o json
