---
apiVersion: v1
kind: Namespace
metadata:
  name: mnc
  labels:
    project: google
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mnc-replica-web-server
  namespace: mnc
  labels:
    project: google
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: lion-server
      labels:
        project: google           # Common Labels
        app: web-server   
    spec:
      containers:
      - name: web-server
        image: jjino/web-app:v1
        ports:
        - containerPort: 80
      - name: cache-server
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: mnc-replica-web-server-xxxx-web-service
  namespace: mnc
  labels:
    app: web-server
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - name: http
      port: 80
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: mnc-replica-web-server-xxxx-cache-service
  namespace: mnc
  labels:
    app: web-server
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - name: redis
      port: 6379
      nodePort: 30008
