---
apiVersion: v1
kind: Secret
metadata:
  name: cid
type: Opaque
data:
  clientSecret: S2pkTVFoxxxxxxxxxxxxxLmtZbROxxxxxENlQgo=
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: cididentity
spec:
  type: 1
  tenantID: "xxxxxx-xxxxx-4c86-a131-xxxx"
  clientID: "xxxx-xxxx-4362-8849-xxxx"
  clientPassword: {"name":"cid","namespace":"controller"}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: cididentitybinding
spec:
  azureIdentity: "cididentity"
  selector: "keyvault"

# kubectl run azure-cli -it --image=mcr.microsoft.com/azure-cli --labels=aadpodidbinding=keyvault /bin/bash
# az login --debug

## test file for keyvault

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-keyvault-reader-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvaultsample
  template:
    metadata:
      labels:
        app: keyvaultsample
        aadpodidbinding: keyvault
      name: keyvaultsample
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            [
              "sh",
              "-c",
              "wget --tries=70 -qO- http://127.0.0.1:8333/secrets/testvalue/",
            ]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Mi"
              cpu: "100m"
            limits:
              memory: "8Mi"
              cpu: "200m"
        - name: az-keyvault-reader-sidecar
          image: cmendibl3/az-keyvault-reader:0.2
          imagePullPolicy: Always
          env:
            - name: AZURE_KEYVAULT_NAME
              value: kv-demoslock-dev
          resources:
            requests:
              memory: "8Mi"
              cpu: "100m"
            limits:
              memory: "16Mi"
              cpu: "200m"
      restartPolicy: Always

#  kubectl logs pod/az-keyvault-reader-test-54c97bb96c-slxr5 -c busybox -n  migaportal-controller
