# for i in {1..100};do curl -s -o /dev/null -w "%{http_code}\n" http://jjservice; done
---
apiVersion: v1 
kind: Namespace
metadata:
  name: gg
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  namespace: gg
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:     
      - image: nginx
        name: nginx-server1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: gg
  labels:
    app: web-server
spec:
  ports:
    - port: 80
  selector:
    app: web-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jjservice
  namespace: gg
spec:
  type: ExternalName
  externalName: web-service.jj.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: v1 
kind: Namespace
metadata:
  name: jj
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  namespace: jj
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:     
      - image: nginx
        name: nginx-server1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: jj
  labels:
    app: web-server
spec:
  ports:
    - port: 80
  selector:
    app: web-server
  type: ClusterIP
