apiVersion: v1
kind: Pod
metadata:
  name: reactjs-pod
  labels:
    component: web
spec:
  containers:
    - name: reactjs-application
      image: jjino/reactjs-application
      ports:
        - containerPort: 3000
        
        
        
# spec:
#   containers:
#     - name: nginx
#       image: nginx
#       ports:
#         - containerPort: 80
