trigger:
- master

resources:
- repo: self

pool: 
  name: miga
  demands:  
  - Agent.ComputerName -equals access-server

steps:
  - task: KubernetesManifest@0
    displayName: kubernetes-deploy
    inputs:
      kubernetesServiceConnection: migaportal-dev-ui-service-account
      namespace: migaportal-controller
      manifests: deployment/agic-ingress-controller.yml
