---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: applicationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: jjino/jwt:v1
        imagePullPolicy: Always
        name: node-image
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /heathz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: applicationservice
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-service-ingress
  namespace: applicationservice
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    #appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: scanslips

spec:
  rules:
  - http:
      paths:
      - path: /users/api/v1/createuser/
        backend:
          serviceName: node-service
          servicePort: 8080
      - path: /users/api/v1/userinfo/
        backend:
          serviceName: node-service
          servicePort: 8080
      - path: /signin/
        backend:
          serviceName: node-service
          servicePort: 8080
