---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range-namespace
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/