apiVersion: v1
kind: Pod
metadata:
  name: cpu-overload
  namespace: cpu-overload
spec:
  containers:
  - name: cpu-overload
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"