---
# namespace creation
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# deployement creation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactjs-application
  namespace: dev
  labels: 
    app: reactjs
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
      - name: reactjs-application
        image: jjino/reactjs-application
        ports:
          - containerPort: 3000
---
# service creation
apiVersion: v1
kind: Service
metadata:
  name: reactjs-application-svc
  namespace: dev
  labels:
    app: reactjs
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3000
    nodePort: 32515
  selector:
    app: reactjs