apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-test
spec:
  containers:
  - name: quota-mem-cpu-test-ctr
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"