---
apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: psql
    tier: backend
    version: master
spec:
  containers:
  - name: psql
    image: postgres
    ports:
      - containerPort: 5432
    volumeMounts:
      - name: pgdata
        mountPath: /var/lib/postgresql/data
  volumes:
  - name: pgdata
    hostPath:
      path: /var/lib/postgres
      type: DirectoryOrCreate
