---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-appdata
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: RollingUpdate #Bydefault (RollingUpdate/Recreate)
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 4
  paused: false
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
      jane: akil
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: web
      labels:
        role: webserver
        version: v3
        tier: frond
        jane: akil
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginxdata
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginxdata
        persistentVolumeClaim:
          claimName: azure-managed-disk-appdata
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    role: web-service
spec:
  selector:
    role: webserver
    # version: 'v3'
    tier: frond
    jane: akil
  type: LoadBalancer
  ports:
  - port: 80

