---
apiVersion: v1
kind: Namespace
metadata:
  name: woolf
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: woolf
  labels:
    app: webdb
    tier: backend
spec:
  containers:
  - name: db-server
    image: mysql
    ports:
      - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password@123
  - name: web-server
    image: nginx
    ports:
      - containerPort: 80

