apiVersion: v1
kind: Pod
metadata:
  name: memory-large-test
spec:
  containers:
  - name: memory-large-test
    image: polinux/stress
    resources:
      limits:
        memory: "1000Gi"
      requests:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]