---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  namespace: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web
      labels:
        app: web-server
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lion-server-service
  namespace: animals
  labels:
    client: lion      
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
  - port: 80
    nodePort: 30001