---
apiVersion: v1
kind: Namespace
metadata:
  name: animals
  labels:
    client: lion
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lion-server
  namespace: animals
  labels:
    client: lion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web
      labels:
        app: web-server
    spec:
      containers:
        - name: web
          image: jjino/web-app:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lion-server-service
  namespace: animals
  labels:
    client: lion
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - port: 80
      nodePort: 30001
