---
apiVersion: v1
kind: Namespace
metadata:
  name: birds
  labels:
    client: duck
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replica
  namespace: birds
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      name: web
      labels:
        role: web
    spec:
      containers:
        - name: web
          image: httpd
          ports:
            - containerPort: 80
        - name: redis-server
          image: redis
          ports:
          - containerPort: 6379