---
apiVersion: v1
kind: Namespace
metadata:
  name: trees
  labels:
    client: palm
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tree-web-server
  namespace: trees
  labels:
    client: palm
spec:
  replicas: 4
  minReadySeconds: 10
  selector:
    matchLabels:
      role: web
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3]}
  template:
    metadata:
      name: web
      labels:
        client: palm
        role: web
        version: v1
    spec:
      containers:
      - name: web
        image: jjino/web-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tree-web-server-service
  namespace: trees
  labels:
    client: palm
spec:
  type: NodePort
  selector:
    role: web
  ports:
    - name: http
      port: 80
      nodePort: 30002